Fixed files with backslashes not reporting any items
foonathan/cppast pull request #139
Opened 2022-05-30 21:28 UTC by MetalSlime0

parse_linemarker was turning double backslashes into quadruple backslashes. Making it instead turn them into single backslashes makes the "lm.value().file == path" comparison true in preprocess() so that p.enable_write() is called.

fixes foonathan/cppast#106

2022-05-30 21:36 UTC, MetalSlime0 commented
I didn't intend for my second commit to be part of the same pull request. Sorry, new to this.

2022-05-31 13:58 UTC, foonathan requested changes
You know how it is: small changes, lots of nitpicks :D Please also reformat; I don't like whitespace inside the parenthesis.

2022-05-31 13:58 UTC, foonathan commented on include/cppast/detail/intrusive_list.hpp
> +            T* next = next_.release();
Nitpick, use auto.

2022-05-31 13:58 UTC, foonathan commented on src/libclang/preprocessor.cpp
> +        if ( starts_with( p, "\\\\" ) )
Please use raw string literals here and throughout the function, the number of backslashes are getting unwieldy.

2022-05-31 13:59 UTC, foonathan commented
> I didn't intend for my second commit to be part of the same pull request. Sorry, new to this.

Thank you, and no problem. When you implement my feedback, please amend and force push so there are two commits: one for the backslashes and one for the intrusive list. I can then rebase.

2022-06-30 15:31 UTC, foonathan commented
I've manually adapted it and merged it. Thanks!

2022-06-30 15:31 UTC, closed without merging